<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<?php $i = $this->view->find;?>
	<div class="row pt-2">
		
		<div class="col-md-3">

		<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?php echo $this->view->usuario->getUserInfor()['nome']?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->usuario->getTotalTweets()['total_tweets']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->usuario->getTotalFollowing()['total_following']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->usuario->getTotalFollowers()['total_followers']?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="GET">
								<div class="input-group mb-3">
									<input type="text" name="find" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<?php if(isset($_GET['find']) && $_GET['find'] != '' ){foreach($this->view->usuarios as $array => $usuario){?>
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col-md-6">
								<?php echo $usuario['nome']?>
								</div>
								<div class="col-md-6 d-flex justify-content-end">
									<div>
										<?php if($usuario['seguindo'] != 1){?>
										<a href="/acao?action=follow&id=<?php echo $usuario['id'].'&find='. $_GET['find']?>" class="btn btn-success">Seguir</a>
										<?php } else{?>
										<a href="/acao?action=unfollow&id=<?php echo $usuario['id'].'&find='. $_GET['find']?>" class="btn btn-danger">Deixar de seguir</a>
										<?php }?>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php }}?>

		</div>
	</div>
</div>